# Site settings
author: Brian Simonton
title: Blog setup
header-img: img/home-bg.png
email: bsimonton78@gmail.com
copyright_name: Brian Simonton
description: > # this means to ignore newlines until "baseurl:"
  first blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bsimonton

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
